"""empty message

Revision ID: 4be7d8fdb73c
Revises: cea9dc740f41
Create Date: 2022-05-31 00:31:34.155932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be7d8fdb73c'
down_revision = 'cea9dc740f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_id', sa.String(), nullable=True))
    op.add_column('shows', sa.Column('venue_id', sa.String(), nullable=True))
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'venue_id')
    op.drop_column('shows', 'venue_id')
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
